config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    root to: 'pages#home'
  get "/team" => "pages#team"
  get "/contact" => "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
   def home
    # ...
  end
  def team
    # ...
  end
  def contact
    # ...
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>PLATFORM</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= render "shared/analytics" %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/contact.html.erb
contact

app/views/pages/home.html.erb
<%= render "shared/bannerhome" %>
<br>

app/views/pages/team.html.erb
team

app/views/shared/_bannerhome.html.erb
<% if user_signed_in? %>
    <div class="container">

      <h1 class="text-center">I'am IN</h1>
     




<% else %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('background.jpg');">
    <div class="banner-content">
      <h1>Log you</h1>
      <p>FIND BEST ENGINEERING TOOLS</p>
      <%= link_to "GET IT", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  
  <div class="copyright">
  <div class="container">
    <div class="col-md-6">
      <p>© 2016 - All Rights with Webenlance</p>
    </div>
    <div class="col-md-6">
      <ul class="bottom_ul">
        <li><a href="#">webenlance.com</a></li>
        <li><a href="#">About us</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Faq's</a></li>
        <li><a href="#">Contact us</a></li>
        <li><a href="#">Site Map</a></li>
      </ul>
    </div>
  </div>
</div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
   <%= image_tag "logo.png" %>   <h13>  Platform</h13>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Text link -->

      <%= link_to "All product", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "team", team_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "contact", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

          <li> <%= link_to "log out", destroy_user_session_path, method: :delete %> </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->

    <%= link_to "ADD TOOLs", root_path, class:"navbar-wagon-item navbar-wagon-button btn"  %>

      <% else %>
      <%= link_to "Sign UP", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "Log in", new_user_session_path, class:"navbar-wagon-item navbar-wagon-button btn" %>
  <% end %>





  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

</div>